### ISSUE TITLE
ModuleNotFoundError: No module named 'optim'

### ISSUE THREAD

**Issue by fromSun2Moon** [VickiCui/Loire#1]
Hi, I tried to train Loire, but it occurs ModuleNotFoundError.
Here is my traceback. Is it related with development environment?
I could not find optim file in library. 
I would like to wait your reply. 
Thanks!

Traceback (most recent call last):
  File "./tools/train.py", line 13, in <module>
    from modules.my_trainer import SupervisedTrainer
  File "/home/ubuntu/shpark/Loire/layout_generator/tools/../lib/modules/my_trainer.py", line 23, in <module>
    from optim import Optimizer
ModuleNotFoundError: No module named 'optim'

**Comment by ckmstydy** [comment]
Hi, Did you solve this problem? bro

**Comment by VickiCui** [comment]
Sorry, I missed a file when uploading the code. optim.py has been uploaded to Loire/layout_generator/lib/

**Comment by fromSun2Moon** [comment]
Dear, VickiCui.
I solved the problem at that time! Thank you!

Sincerely
SanheePark

2021년 6월 21일 (월) 오전 11:20, Wanqing Cui ***@***.***>님이 작성:

**Comment by VickiCui** [comment]
您好，您的邮件我已经收到，我会第一时间处理。
